### ISSUE TITLE
Arrow Head disappears

### ISSUE THREAD

**Issue by msimonc** [xbsoftware/enjoyhint#15]
Hi, thanks for the repo,

When I run the demo arrow heads are there,

but when I import css and js into our project arrow heads are gone, everything else works fine,

all help appreciated,

**Comment by gmrx38** [comment]
Hello !
I've got the same issue.
I've only a line between my element and the label description..
Did I forget something?

Thanks you !

**Comment by msimonc** [comment]
Still open, thanks

**Comment by gmrx38** [comment]
"Still open", but.. why did you closed so ?
It's a duplicate issue with the #9 ?

**Comment by chris-herring** [comment]
Had the same issue and in my case it was due to using the base tag. The arrow head is rendered using a SVG marker and the url reference it uses will have issues when you use a base tag e.g. [see here](http://stackoverflow.com/questions/18259032/using-base-tag-on-a-page-that-contains-svg-marker-elements-fails-to-render-marke). So you can either remove the base tag, update the code to correctly reference the marker uri or update the code to render the arrow as another path instead of a marker like what is done with the line.
