### ISSUE TITLE
Uncaught TypeError: $body.enjoyhint is not a function     at h (enjoyhint.min.js:1)     at new EnjoyHint (enjoyhint.min.js:1)     at HTMLDocument.<anonymous> (User:159)     at fire (jquery-1.10.2.js:3048)     at Object.fireWith [as resolveWith] (jquery-1.10.2.js:3160)     at Function.ready (jquery-1.10.2.js:433)     at HTMLDocument.completed (jquery-1.10.2.js:104)

### ISSUE THREAD

**Issue by CandiceDong** [xbsoftware/enjoyhint#57]

**Comment by fscardua** [comment]
+1

**Comment by KaueSantos** [comment]
+1

**Comment by HectorBlisS** [comment]
+1

**Comment by Xerotico** [comment]
+1

**Comment by VaskaDagamas** [comment]
+1

**Comment by christinegomes95** [comment]
Make sure you have imported your jquery.js and jquery.enjoyhint.js files before your enjoyhint.js file.
From what I have noticed, this issue arises because the .enjoyhint class is attached to body tag from the jquery.enjoyhint.js file but is not available when enjoyhint.js is loaded due to the order in which you import your files.

You may also find the process of how I integrated enjoyhint into my angular 4 project here:
https://github.com/xbsoftware/enjoyhint/issues/101#issuecomment-456008064

Hope this helps.

**Comment by ShvedkaSvetka** [comment]
Hello, thank you for taking time filling this issue! 

Every issue should provide the necessary information for us to investigate. This explains why your issue has been closed. If you still have the issue, please create it again and provide information how to reproduce the issue.
